version: "master-{build}"

os: Windows Server 2012 R2
platform:
  - x64

environment:
  matrix:
    - ruby_version: "200"
    - ruby_version: "200-x64"
    - ruby_version: "21"
    - ruby_version: "21-x64"
    - ruby_version: "22"
    - ruby_version: "22-x64"

clone_folder: c:\projects\chef
clone_depth: 1
skip_tags: true
branches:
  only:
    - master

cache:
  - C:\Ruby200\lib\ruby\gems\2.0.0
  - C:\Ruby200\bin
  - C:\Ruby200-x64\lib\ruby\gems\2.0.0
  - C:\Ruby200\bin
  - C:\Ruby21\lib\ruby\gems\2.1.0
  - C:\Ruby21\bin
  - C:\Ruby21-x64\lib\ruby\gems\2.1.0
  - C:\Ruby21\bin
  - C:\Ruby22\lib\ruby\gems\2.2.0
  - C:\Ruby22\bin
  - C:\Ruby22-x64\lib\ruby\gems\2.2.0
  - C:\Ruby22\bin

install:
  - systeminfo
  - winrm quickconfig -q
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - echo %PATH%
  - ruby --version
  - gem install bundler --quiet --no-ri --no-rdoc || gem install bundler --quiet --no-ri --no-rdoc || gem install bundler --quiet --no-ri --no-rdoc
  - gem install rubygems-pkg/rubygems-update-2.4.6.gem
  - update_rubygems
  - gem --version
  - bundler --version

build_script:
  - bundle install || bundle install || bundle install

test_script:
  - SET SPEC_OPTS=--format progress
  - bundle exec rake spec
